name: Lint Project

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install packages
        run: pnpm install
      
      - name: Format
        run: pnpm run format

      - name: Commit Format
        run: |
          git add -N . # 新規ファイルを含める
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "chore: fix format."
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Exec Lint
        run: pnpm run lint
